"""empty message

Revision ID: 74dbd304a208
Revises: 
Create Date: 2017-10-28 16:55:55.788050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74dbd304a208'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcasts', schema=None) as batch_op:
        batch_op.drop_column('subtitle')

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('begin', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('end', sa.Time(), nullable=True))
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('end')
        batch_op.drop_column('begin')

    with op.batch_alter_table('podcasts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.VARCHAR(length=256), nullable=True))

    # ### end Alembic commands ###
