"""empty message

Revision ID: df76cfe57893
Revises: 74dbd304a208
Create Date: 2017-10-28 22:16:44.745249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df76cfe57893'
down_revision = '74dbd304a208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcasts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcasts', schema=None) as batch_op:
        batch_op.drop_column('public')

    # ### end Alembic commands ###
