"""empty message

Revision ID: fcd611caa8be
Revises: ecdc3d52ced8
Create Date: 2017-10-29 18:31:10.962907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd611caa8be'
down_revision = 'ecdc3d52ced8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'labels', ['label_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('label_id')

    # ### end Alembic commands ###
